Add Object.assign native function back to global
* there are very f*cking bug in traceur package which is used in di-ts -> di to write default es6 support.
* Traceur Object.assign not support more then 2 arguments to extend passed object
* react-router uses the native Object.assign function by default & uses with more then 2 arguments. Traceur not allow it
* Problem without this is not extending history in react-router/lib/match.js with match function & throws TypeError: history.match is not a function